### ISSUE TITLE
laptop quite hot 8750

### ISSUE THREAD

**Issue by sidbmw** [LuletterSoul/Dell-XPS-15-9570-macOS-Mojave#31]
Is it just me or are ur laptops burning hot as well. 

It was warm near USB C port on windows as well as I have a dongle thing attached but uh seems louder and possibly warmer on Mojave...

Also, is there a battery tweak or other tweaks required? I believe I have clover 4681 installed and not the newest one. Is that fine?

**Comment by sidbmw** [comment]
Seems to be at max freq the whole time as well

**Comment by sidbmw** [comment]
![image](https://user-images.githubusercontent.com/16989022/59893892-62e28a00-9393-11e9-9194-216e01e5be9e.png)

**Comment by andresandiah** [comment]
Hi, try downloading this file from Lulettersouls response on this post.

[SSDT-Config.zip](https://github.com/LuletterSoul/Dell-XPS-15-9570-macOS-Mojave/files/3075808/SSDT-Config.zip)

_Originally posted by @LuletterSoul in https://github.com/LuletterSoul/Dell-XPS-15-9570-macOS-Mojave/issues/2#issuecomment-482779467_

Extract it and copy the contents to de ACPI->Others  folder inside your CLOVER (EFI)

**Comment by sidbmw** [comment]
Done, this is what my CLOVER file looks like now.


[CLOVER.zip](https://github.com/LuletterSoul/Dell-XPS-15-9570-macOS-Mojave/files/3312837/CLOVER.zip)


My trackpad doesn't seem to be perfect either. Acts weird (jumps a bit at times).

**Comment by andresandiah** [comment]
Ok, the ssdt wasn't in the correct location, I've moved to the correct one and also cleaned up a bit of the unnecesary files on your config.

[CLOVER 2.zip](https://github.com/LuletterSoul/Dell-XPS-15-9570-macOS-Mojave/files/3312857/CLOVER.2.zip)

just drop this clover folder over the old one and when finder asks, click "replace"

Edit: After everuthing is done, remember to run the command

_sudo kextcache -i /_

and then reboot your system.

Trackpad performance is as good as it gets for now, definitely is the best one out of multiple EFI's i tried

**Comment by sidbmw** [comment]
Oh....I haven't been running that command NO WONDER HAHAHAH

Also installed the audio patch but didn't seem to fix. Would running that command fix it as well?

Thanks

**Comment by andresandiah** [comment]
make sure you are running this file from the alc plug:

"install双击自动安装.command"

and not the other one with a similar name. The other one is for uninstalling it.

The fix is essentially to make the headphone plug not distort everytime you plug ion something to the 3.5 mm jack.

once you do that just reboot.

Just for general knowledge, everytime you inject a new kext, or make a change to ssdt its a good rule of thumb to run the sudo kextcache command.

**Comment by sidbmw** [comment]
Ok will reboot now. Btw any idea on a fix for kernel panics?

**Comment by andresandiah** [comment]
you mean the random ones at boot?

For me it got solved by injexting the following kexts into Library/extensions:

_VoodooI2C.kext
VoodooI2CHID.kext
VoodooPS2Controller.kext_

search for the guide by rehabman on injexting kexts and how to do it using KextBeast. that should solve it. once again, once you do it run sudo kextcache

**Comment by sidbmw** [comment]
WIll try tomorrow. 

Thank you very much!!!

Have a great day!

**Comment by sidbmw** [comment]
Audio doesn't seem to be fixed yet. I ran the file, ran the kextcache command and then rebooted. When unplugged I get blasted with a random noise on my earphones.

![image](https://user-images.githubusercontent.com/16989022/59930727-6f0d2c80-9411-11e9-986c-f6e18badf6cf.png)

**Comment by sidbmw** [comment]
![image](https://user-images.githubusercontent.com/16989022/59930834-b72c4f00-9411-11e9-8330-6e64d268c336.png)


Ran as sudo this time. Will reboot and check after running the kextcache command


Yep still doesn't work

**Comment by sidbmw** [comment]
Unplugged audio a couple times, started charging, stopped charging and I guess it works now????

I'm confused lol

**Comment by sidbmw** [comment]
Oh and I've been updating CLOVER under the OS partition....not sure if that's the right one

![image](https://user-images.githubusercontent.com/16989022/59931882-f22f8200-9413-11e9-88c4-fe5e9154d70b.png)

**Comment by andresandiah** [comment]
Clover must be updated on your EFI partition, not the ¨Mojave¨ partition.

**Comment by sidbmw** [comment]
Gotcha!  I copy pasted the files you gave me to the EFI partition. Would updating clover be a separate thing? I will run the CLOVER install file 4968 shortly with the 3 options enabled as you had said in your guide.

**Comment by sidbmw** [comment]
![image](https://user-images.githubusercontent.com/16989022/59933743-f8bff880-9417-11e9-96bc-1f30b79cbf58.png)

I can't seem to select EFI, it skips right past that screen.

**Comment by andresandiah** [comment]
if clover is behaving normally, there is no need to update it everytime. 

Sorry i go confused when i saw an EFI folder inside of the Mojave Drive. As soon as clover installation finishes you should see an EFI volume in finder, copy the CLOVER folder I sent you to that folder.

**Comment by sidbmw** [comment]
![image](https://user-images.githubusercontent.com/16989022/59938660-a4227a80-9423-11e9-84b0-4a164ed7af01.png)

Directly into EFI on inside the EFI folder in EFI lol

**Comment by andresandiah** [comment]
in the EFI folder which is inside EFI volume

**Comment by sidbmw** [comment]
ok
